import React from 'react';
import { NextResponse } from 'next/server';
import { prisma } from '@/src/lib/db';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  title: { fontSize: 18, marginBottom: 8, fontWeight: 'bold' },
  subtitle: { fontSize: 12, marginBottom: 20, color: '#444' },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 8 },
  para: { fontSize: 10, marginBottom: 6, lineHeight: 1.4 },
  score: { fontSize: 24, fontWeight: 'bold', marginVertical: 8 },
  table: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderColor: '#ddd', paddingVertical: 4 },
  col1: { width: '20%', fontSize: 9 },
  col2: { width: '50%', fontSize: 9 },
  col3: { width: '15%', fontSize: 9 },
  col4: { width: '15%', fontSize: 9 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#666' },
});

function ReportDocument({
  companyName,
  report,
  issues,
  recommendations,
}: {
  companyName: string;
  report: { complianceScore: number; riskLevel: string };
  issues: { ruleName: string; status: string; message: string }[];
  recommendations: string[];
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Audit Readiness Report</Text>
        <Text style={styles.subtitle}>
          {companyName} | South African Financial Compliance Assessment
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <Text style={styles.para}>
            This report provides a compliance assessment for {companyName}, aligned with IFRS,
            the South African Companies Act, and SARS tax requirements. It is intended to identify
            risks, highlight gaps, and assist with audit preparation. This is not legal advice.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Compliance Score</Text>
          <Text style={styles.score}>{report.complianceScore}%</Text>
          <Text style={styles.para}>Risk Level: {report.riskLevel}</Text>
        </View>

        {issues.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Key Issues Detected</Text>
            {issues.map((issue, i) => (
              <View key={i} style={styles.tableRow}>
                <Text style={styles.col1}>{issue.status}</Text>
                <Text style={styles.col2}>{issue.ruleName}</Text>
                <Text style={{ ...styles.col3, width: '80%' }}>{issue.message}</Text>
              </View>
            ))}
          </View>
        )}

        {recommendations.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Recommendations</Text>
            {recommendations.map((rec, i) => (
              <Text key={i} style={styles.para}>• {rec}</Text>
            ))}
          </View>
        )}

        <Text style={styles.footer}>
          Generated by Finance Compliance App. For audit preparation purposes only. Not legal advice.
        </Text>
      </Page>
    </Document>
  );
}

export async function GET(
  _request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const report = await prisma.complianceReport.findUnique({
      where: { id: params.id },
      include: { company: true, trialBalance: { include: { checkResults: { include: { rule: true } } } } },
    });

    if (!report) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    const data = JSON.parse(report.summaryJson) as {
      issues?: { ruleName: string; status: string; message: string }[];
      recommendations?: string[];
    };

    const issues = (data.issues || report.trialBalance.checkResults)
      .filter((r: { status?: string }) => r.status !== 'COMPLIANT')
      .map((r: { ruleName?: string; rule?: { name: string }; status?: string; message?: string }) => ({
        ruleName: r.ruleName ?? r.rule?.name ?? 'Check',
        status: r.status ?? 'WARNING',
        message: r.message ?? '',
      }));

    const recommendations = data.recommendations ?? issues.map((i: { message?: string }) => i.message ?? '');

    const doc = (
      <ReportDocument
        companyName={report.company.name}
        report={{ complianceScore: report.complianceScore, riskLevel: report.riskLevel }}
        issues={issues}
        recommendations={recommendations}
      />
    );
    const blob = await pdf(doc).toBlob();

    const buffer = Buffer.from(await blob.arrayBuffer());
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="audit-readiness-${report.company.name.replace(/\s/g, '-')}.pdf"`,
      },
    });
  } catch (error) {
    console.error('[API] PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
